### ISSUE TITLE
Health Monitors to pool

### ISSUE THREAD

**Issue by ns500** [F5Networks/bigsuds#5]
May I ask how to set up Health Monitors to pool?

**Comment by caphrim007** [comment]
Out of curiosity have you asked for any examples on the devcentral.f5.com site?

The admins over there usually want us to condense code examples into the codeshare section of the site. I'd be happy to extract code examples from devcentral and put them in an `examples/` directory here if there's an interest in doing that.

I'd include them on Codeshare as well though so-as not to have others miss out on them.

**Comment by ns500** [comment]
thank you very much.
